### ISSUE TITLE
Is quantisation supported?

### ISSUE THREAD

**Issue by kDanil** [kleisauke/libvips-packaging#2]
Hi,

According to https://fossies.org/linux/vips/libvips/foreign/pngsave.c to take advantage of PNG quantisation libvips require to be compiled with libimagequant.

Quantisation parameters are not making any difference for me.

Is quantisation supported?

**Comment by kleisauke** [comment]
libimagequant is GPL so you'll need to use a custom, globally-installed libvips that has itself been compiled with support for libimagequant.

The prebuilt binaries provided by NetVips for libvips and its dependencies do not include GPL-licensed or patent-encumbered software.

**Comment by kDanil** [comment]
Thank you!
